USE [master]
GO

/****** Object:  Database [LivroDeReceitas]    Script Date: 22/06/2018 12:27:45 ******/
CREATE DATABASE [LivroDeReceitas]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LivroDeReceitas', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SSQLSERVER\MSSQL\DATA\LivroDeReceitas.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LivroDeReceitas_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SSQLSERVER\MSSQL\DATA\LivroDeReceitas_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LivroDeReceitas] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LivroDeReceitas].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LivroDeReceitas] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LivroDeReceitas] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LivroDeReceitas] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LivroDeReceitas] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LivroDeReceitas] SET ARITHABORT OFF 
GO

ALTER DATABASE [LivroDeReceitas] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [LivroDeReceitas] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LivroDeReceitas] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LivroDeReceitas] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LivroDeReceitas] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LivroDeReceitas] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LivroDeReceitas] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LivroDeReceitas] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LivroDeReceitas] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LivroDeReceitas] SET  ENABLE_BROKER 
GO

ALTER DATABASE [LivroDeReceitas] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LivroDeReceitas] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LivroDeReceitas] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LivroDeReceitas] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LivroDeReceitas] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LivroDeReceitas] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LivroDeReceitas] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LivroDeReceitas] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LivroDeReceitas] SET  MULTI_USER 
GO

ALTER DATABASE [LivroDeReceitas] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LivroDeReceitas] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LivroDeReceitas] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LivroDeReceitas] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LivroDeReceitas] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LivroDeReceitas] SET  READ_WRITE 
GO


